version: 2


sources:

  - name: raw

    schema: ny_taxi


    tables:

      - name: yellow_tripdata


        config:

          loaded_at_field: "CAST(tpep_pickup_datetime AS TIMESTAMP)"


          freshness:

            warn_after:

              count: 3650

              period: day


            error_after:

              count: 7300

              period: day