name: dbt CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main


jobs:

  dbt-build:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install dbt-bigquery
      run: |
        pip install dbt-bigquery


    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Create GCP credentials file
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > ${{ runner.temp }}/gcp-key.json


    - name: Create dbt profile
      run: |
        mkdir -p ~/.dbt

        cat > ~/.dbt/profiles.yml <<EOF
        taxi_rides_ny:
          outputs:
            dev:
              dataset: taxi_rides_ny
              location: US
              method: service-account
              keyfile: ${{ runner.temp }}/gcp-key.json
              priority: interactive
              project: ${{ secrets.GCP_PROJECT_ID }}
              threads: 4
              type: bigquery
          target: dev
        EOF


    - name: Run dbt build
      working-directory: 03-data-transformation-dbt/taxi_rides_ny
      run: |
        dbt deps
        dbt build