name: dbt CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main


jobs:

  dbt-test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install uv
        uses: astral-sh/setup-uv@v5


      - name: Install dependencies
        run: |
          cd 04-analytics-engineering
          uv sync